name: Townyinfo
version: ${project.version}
main: honnisha.townyinfo.Townyinfo
api-version: 1.16
authors: [ Honnisha ]
depend: [ Towny ]
softdepend: [ PlaceholderAPI, DiscordSRV, BetonQuest, SiegeWar ]

commands:
  townyinfo:
    usage: '§e/townyinfo'
    aliases: [ ti ]